CREATE TABLE IF NOT EXISTS hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        VARCHAR(300)                            NOT NULL,
    uri        VARCHAR(1000)                           NOT NULL,
    ip         VARCHAR(100)                            NOT NULL,
    created_on TIMESTAMP                               NOT NULL,
    PRIMARY KEY (id)
);
