version: '3.8'
services:

  stats-server:
    build: ./ewm-stats-service
    image: ewm-stats-service
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SERVER_PORT=9090


  stats-db:
    image: postgres:14
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=stats-db

  ewm-service:
    build: ewm-main-service
    image: ewm-main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-service-db:5432/ewm-service-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STATS_SERVER_URL=http://ewm-stats-service:9090
      - SERVER_PORT=8080

  ewm-db:
    image: postgres:14
    container_name: ewm-service-db
    ports:
      - "5433:5432"
    environment:

      - POSTGRES_DB=ewm-service-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
